def piky():
    letra = [
        "Le digo hola, ella me dice goodbye",
        "Le digo: \"nena, como tú ya no hay\"",
        "Dice que tiene novio, pero yo no le creo",
        "Y es que se complica cada vez que la veo-eo",
        "Suena la música y lo que yo quiero",
        "Es bailar contigo, nena, pero yo no puedo",
        "No puedo, me dice: \"yo no quiero\"",
        "Pero se complica, yo no entiendo por qué es tan",
        "Picky, picky, picky, picky, picky",
        "Demasiado picky, picky, picky, picky, picky",
        "Si yo le salgo por la izquierda, se va pa' la derecha",
        "No sé lo que le pasa, conmigo ella no quiere bailar",
        "Picky, picky, picky, picky, picky",
        "Demasiado picky, picky, picky, picky, picky",
        "Si yo le salgo por la izquierda, se va pa' la derecha",
        "No sé lo que le pasa, conmigo ella no quiere bailar",
        "Ella me gusta, pero nunca me hace caso",
        "Ella me mira como si fuera un payaso",
        "Y aunque lo intente, al final no tiene caso",
        "Dime qué pasó, ¿cuál es tu rechazo?",
        "Why?",
        "Me ignoras y te das la vuelta sin siquiera hablarme",
        "Tell me why",
        "Pero dime cómo hacer para convencerla a usted",
        "Si yo quería hablarle, saludarle, conocerla bien",
        "Yo quería decirle que me encanta",
        "Pero se complica, yo no entiendo por qué es tan",
        "Picky, picky, picky, picky, picky",
        "Demasiado picky, picky, picky, picky, picky",
        "Si yo le salgo por la izquierda, se va pa' la derecha",
        "No sé lo que le pasa, conmigo ella no quiere bailar",
        "Picky, picky, picky, picky, picky",
        "Demasiado picky, picky, picky, picky, picky",
        "Si yo le salgo por la izquierda, se va pa' la derecha",
        "No sé lo que le pasa, conmigo ella no quiere bailar",
        "Nena, tú lo sabes, llevo tiempo tras de ti, ah",
        "Y es que yo no entiendo por qué tú me trata' así, ah",
        "Y yo lo único que quiero es bailar",
        "Y tú me ves, te das la vuelta y te vas",
        "Le digo hola, ella me dice goodbye (goodbye)",
        "Le digo: \"nena, como tú ya no hay\"",
        "Dice que tiene novio, pero yo no le creo",
        "Y es que se complica cada vez que la veo-eo",
        "Suena la música y lo que yo quiero",
        "Es bailar contigo, nena, pero yo no puedo",
        "No puedo, me dice: \"yo no quiero\"",
        "Pero se complica, yo no entiendo por qué es tan",
        "Picky, picky, picky, picky, picky",
        "Demasiado picky, picky, picky, picky, picky",
        "Si yo le salgo por la izquierda, se va pa' la derecha",
        "No sé lo que le pasa, conmigo ella no quiere bailar",
        "Picky, picky, picky, picky, picky",
        "Demasiado picky, picky, picky, picky, picky",
        "Si yo le salgo por la izquierda, se va pa' la derecha",
        "No sé lo que le pasa, conmigo ella no quiere bailar"
    ]
    return letra